#!/bin/bash
# Copyright (c) 2016 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.
read p
#set >> /tmp/pw
if [ $PAM_USER = "root" ]
then
        exit 0;
fi

if [ "$PAM_TYPE" = "auth" ]; then

    if [ $( id -g $PAM_USER ) = "503" ]; then
    #Workstationuser can login only from its workstation
       if [ "$HOSTNAME" = "$PAM_USER" ]; then
          exit 0
       else
          exit 1
       fi
    fi
    mkdir -p /tmp/groups
    MOUNTED=$( mount | grep '/tmp/groups' )
    if [ "$MOUNTED" ]
    then
        /bin/umount /tmp/groups &>/dev/null
    fi
    /sbin/mount.cifs //admin/groups /tmp/groups -o user=$PAM_USER,password=$p
    MOUNTED=$( mount | grep '/tmp/groups' )
    if [ "$MOUNTED" ]
    then
        exit 0
    else
        exit 1
    fi
fi
if [ "$PAM_TYPE" = "close_session" ]; then
    if [ $PAM_SERVICE = "gdm" -o $PAM_SERVICE = "kdm" -o $PAM_SERVICE = "login" -o $PAM_SERVICE = "xdm" ]; then
        /bin/umount /tmp/groups &>/dev/null
    fi
    exit 0
fi

